### ISSUE TITLE
cant map ports

### ISSUE THREAD

**Issue by felixrieg** [arneboockmeyer/docker-network-simulator#5]
I made a small test network like this:

network.yaml
```
setup:
    version: '3'
    services:
      node0:
        image: test
        network_mode: "none"
        ports:
          - "9944:9944"
      node1:
        image: test
        network_mode: "none"
      node2:
        image: test
        network_mode: "none"
events:
    event1:
        seconds: 100
        do:
            stopContainer: ["node1"]
```
But when i check with `docker ps` there is no port mapping, did i do something wrong or is there an issue
```
[felix:~]$ docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS          PORTS     NAMES
fc84ad877456   test      "/bin/sh -c './utxo-…"   26 seconds ago   Up 25 seconds             networksimulator_node1_1
8179ae4a5be1   test      "/bin/sh -c './utxo-…"   26 seconds ago   Up 25 seconds             networksimulator_node0_1
2a6809e7e0a1   test      "/bin/sh -c './utxo-…"   26 seconds ago   Up 25 seconds             networksimulator_node2_1
```
